import { defineType } from 'sanity';
import { BackgroundShadeInput } from '../../components/BackgroundShadeInput';

export default defineType({
  name: 'caseStudiesPage',
  title: 'Case Studies Page',
  type: 'document',
  fieldsets: [
    {
      name: 'seo',
      title: 'Search Results Description (optional)',
      description:
        'If left empty, search engines will extract the description from page content.',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'ogImage',
      title: 'Social Media Preview Image (optional)',
      description:
        'Also called OG Image. The image shown when this page is shared on social media. If left empty, social media platforms may show no preview image or extract one from the page.',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'heroFields',
      title: '🎯 Hero Section',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'introFields',
      title: '📝 Intro Section',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'filterFields',
      title: '🔍 Filter Section',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'boxFields',
      title: '📦 Box Styling',
      description: 'Customize the appearance of case study boxes in the grid',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'modalFields',
      title: '🪟 Modal Styling',
      description: 'Customize the appearance of the case study modal',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'caseStudiesFields',
      title: '📋 Case Studies',
      options: { collapsible: true, collapsed: false },
    },
  ],
  groups: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'intro', title: 'Intro' },
    { name: 'filter', title: 'Filter' },
    { name: 'boxStyling', title: 'Box Styling' },
    { name: 'modalStyling', title: 'Modal Styling' },
    { name: 'caseStudies', title: 'Case Studies' },
  ],
  fields: [
    // Page Title (SEO)
    {
      name: 'title',
      title: 'Page Title',
      type: 'string',
      description: 'This will be used as the SEO title in search results.',
      initialValue: 'Case Studies',
    },
    {
      name: 'metaDescription',
      title: 'Description',
      type: 'text',
      rows: 3,
      fieldset: 'seo',
      description:
        'The short preview text that appears under your title in Google search results. Keep it under 160 characters.',
      validation: (Rule) => Rule.max(160).warning('Keep under 160 characters'),
    },
    {
      name: 'ogImage',
      title: 'Image',
      type: 'image',
      fieldset: 'ogImage',
      description: 'Recommended size: 1200×630 pixels.',
      options: { hotspot: true },
    },

    // Hero Section
    {
      name: 'heroBackgroundColorType',
      title: 'Background Color',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'primary',
    },
    {
      name: 'heroBackgroundColorShade',
      title: 'Background Shade',
      type: 'number',
      group: 'hero',
      fieldset: 'heroFields',
      initialValue: 90,
      hidden: ({ parent }) => parent?.heroBackgroundColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'heroBackgroundCustomColor',
      title: 'Custom Background Color',
      type: 'simplerColor',
      group: 'hero',
      fieldset: 'heroFields',
      hidden: ({ parent }) => parent?.heroBackgroundColorType !== 'custom',
    },
    {
      name: 'heroHeading',
      title: 'Heading',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      description: 'Main heading text',
    },
    {
      name: 'heroHeadingHighlight',
      title: 'Heading Highlight',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      description: 'Text within heading to italicize (optional)',
    },
    {
      name: 'heroHighlightColorType',
      title: 'Highlight Color',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
      hidden: ({ parent }) => !parent?.heroHeadingHighlight,
    },
    {
      name: 'heroHighlightColorShade',
      title: 'Highlight Shade',
      type: 'number',
      group: 'hero',
      fieldset: 'heroFields',
      initialValue: 0,
      hidden: ({ parent }) =>
        !parent?.heroHeadingHighlight ||
        parent?.heroHighlightColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'heroHighlightCustomColor',
      title: 'Custom Highlight Color',
      type: 'simplerColor',
      group: 'hero',
      fieldset: 'heroFields',
      hidden: ({ parent }) =>
        !parent?.heroHeadingHighlight ||
        parent?.heroHighlightColorType !== 'custom',
    },
    {
      name: 'heroShowDivider',
      title: 'Show Divider',
      type: 'boolean',
      group: 'hero',
      fieldset: 'heroFields',
      initialValue: true,
    },
    {
      name: 'heroDividerColorType',
      title: 'Divider Color',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
      hidden: ({ parent }) => !parent?.heroShowDivider,
    },
    {
      name: 'heroDividerColorShade',
      title: 'Divider Shade',
      type: 'number',
      group: 'hero',
      fieldset: 'heroFields',
      initialValue: 0,
      hidden: ({ parent }) =>
        !parent?.heroShowDivider || parent?.heroDividerColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'heroDividerCustomColor',
      title: 'Custom Divider Color',
      type: 'simplerColor',
      group: 'hero',
      fieldset: 'heroFields',
      hidden: ({ parent }) =>
        !parent?.heroShowDivider || parent?.heroDividerColorType !== 'custom',
    },
    {
      name: 'heroTagline',
      title: 'Tagline',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      description: 'Subtitle text below heading',
    },
    {
      name: 'heroTaglineColor',
      title: 'Tagline Color',
      type: 'string',
      group: 'hero',
      fieldset: 'heroFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'muted',
      hidden: ({ parent }) => !parent?.heroTagline,
    },

    // Intro Section
    {
      name: 'introTitle',
      title: 'Title',
      type: 'string',
      group: 'intro',
      fieldset: 'introFields',
      description: 'Section title (e.g., "Our Work")',
    },
    {
      name: 'introTitleColorType',
      title: 'Title Color',
      type: 'string',
      group: 'intro',
      fieldset: 'introFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
      hidden: ({ parent }) => !parent?.introTitle,
    },
    {
      name: 'introTitleColorShade',
      title: 'Title Shade',
      type: 'number',
      group: 'intro',
      fieldset: 'introFields',
      initialValue: 0,
      hidden: ({ parent }) =>
        !parent?.introTitle || parent?.introTitleColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'introTitleCustomColor',
      title: 'Custom Title Color',
      type: 'simplerColor',
      group: 'intro',
      fieldset: 'introFields',
      hidden: ({ parent }) =>
        !parent?.introTitle || parent?.introTitleColorType !== 'custom',
    },
    {
      name: 'introDescription',
      title: 'Description',
      type: 'portableText',
      group: 'intro',
      fieldset: 'introFields',
      description: 'Description paragraph with rich text support',
    },
    {
      name: 'introDescriptionColor',
      title: 'Description Color',
      type: 'string',
      group: 'intro',
      fieldset: 'introFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'base',
      hidden: ({ parent }) => !parent?.introDescription,
    },
    {
      name: 'introFooter',
      title: 'Footer',
      type: 'text',
      rows: 2,
      group: 'intro',
      fieldset: 'introFields',
      description: 'Italic footer text below description',
    },
    {
      name: 'introFooterColorType',
      title: 'Footer Color',
      type: 'string',
      group: 'intro',
      fieldset: 'introFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
      hidden: ({ parent }) => !parent?.introFooter,
    },
    {
      name: 'introFooterColorShade',
      title: 'Footer Shade',
      type: 'number',
      group: 'intro',
      fieldset: 'introFields',
      initialValue: 0,
      hidden: ({ parent }) =>
        !parent?.introFooter || parent?.introFooterColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'introFooterCustomColor',
      title: 'Custom Footer Color',
      type: 'simplerColor',
      group: 'intro',
      fieldset: 'introFields',
      hidden: ({ parent }) =>
        !parent?.introFooter || parent?.introFooterColorType !== 'custom',
    },

    // Filter Section
    {
      name: 'filterActiveColorType',
      title: 'Active Button Color',
      type: 'string',
      group: 'filter',
      fieldset: 'filterFields',
      description: 'Background color for active filter button',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
    },
    {
      name: 'filterActiveColorShade',
      title: 'Active Button Shade',
      type: 'number',
      group: 'filter',
      fieldset: 'filterFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.filterActiveColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'filterActiveCustomColor',
      title: 'Custom Active Button Color',
      type: 'simplerColor',
      group: 'filter',
      fieldset: 'filterFields',
      hidden: ({ parent }) => parent?.filterActiveColorType !== 'custom',
    },
    {
      name: 'filterActiveTextColor',
      title: 'Active Button Text',
      type: 'string',
      group: 'filter',
      fieldset: 'filterFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'contrast',
    },
    {
      name: 'filterInactiveColorType',
      title: 'Inactive Button Border Color',
      type: 'string',
      group: 'filter',
      fieldset: 'filterFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'filterInactiveColorShade',
      title: 'Inactive Button Border Shade',
      type: 'number',
      group: 'filter',
      fieldset: 'filterFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.filterInactiveColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'filterInactiveCustomColor',
      title: 'Custom Inactive Button Border',
      type: 'simplerColor',
      group: 'filter',
      fieldset: 'filterFields',
      hidden: ({ parent }) => parent?.filterInactiveColorType !== 'custom',
    },
    {
      name: 'filterInactiveTextColor',
      title: 'Inactive Button Text',
      type: 'string',
      group: 'filter',
      fieldset: 'filterFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'muted',
    },

    // Box Styling Section
    {
      name: 'boxBgColorType',
      title: 'Box Background Color',
      type: 'string',
      group: 'boxStyling',
      fieldset: 'boxFields',
      description: 'Default background color for case study boxes',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'boxBgColorShade',
      title: 'Box Background Shade',
      type: 'number',
      group: 'boxStyling',
      fieldset: 'boxFields',
      initialValue: 95,
      hidden: ({ parent }) => parent?.boxBgColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'boxBgCustomColor',
      title: 'Custom Box Background Color',
      type: 'simplerColor',
      group: 'boxStyling',
      fieldset: 'boxFields',
      hidden: ({ parent }) => parent?.boxBgColorType !== 'custom',
    },
    {
      name: 'boxHoverBgColorType',
      title: 'Box Hover Background Color',
      type: 'string',
      group: 'boxStyling',
      fieldset: 'boxFields',
      description: 'Background color when hovering over a box',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
    },
    {
      name: 'boxHoverBgColorShade',
      title: 'Box Hover Background Shade',
      type: 'number',
      group: 'boxStyling',
      fieldset: 'boxFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.boxHoverBgColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'boxHoverBgCustomColor',
      title: 'Custom Box Hover Background Color',
      type: 'simplerColor',
      group: 'boxStyling',
      fieldset: 'boxFields',
      hidden: ({ parent }) => parent?.boxHoverBgColorType !== 'custom',
    },
    {
      name: 'tagColorType',
      title: 'Service Tag Color',
      type: 'string',
      group: 'boxStyling',
      fieldset: 'boxFields',
      description: 'Color for service tags displayed on each box',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'tagColorShade',
      title: 'Service Tag Shade',
      type: 'number',
      group: 'boxStyling',
      fieldset: 'boxFields',
      initialValue: 50,
      hidden: ({ parent }) => parent?.tagColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'tagCustomColor',
      title: 'Custom Service Tag Color',
      type: 'simplerColor',
      group: 'boxStyling',
      fieldset: 'boxFields',
      hidden: ({ parent }) => parent?.tagColorType !== 'custom',
    },
    {
      name: 'ctaTextColor',
      title: 'CTA Text Color',
      type: 'string',
      group: 'boxStyling',
      fieldset: 'boxFields',
      description: 'Color for "View Case" text on hover',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'contrast',
    },

    // Modal Styling Section
    {
      name: 'modalLeftBgColorType',
      title: 'Modal Left Panel Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      description: 'Background color for the left panel of the modal',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'modalLeftBgColorShade',
      title: 'Modal Left Panel Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 95,
      hidden: ({ parent }) => parent?.modalLeftBgColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalLeftBgCustomColor',
      title: 'Custom Modal Left Panel Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalLeftBgColorType !== 'custom',
    },
    {
      name: 'modalBackdropColorType',
      title: 'Modal Backdrop Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      description: 'Color for the semi-transparent backdrop behind the modal',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
    },
    {
      name: 'modalBackdropColorShade',
      title: 'Modal Backdrop Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.modalBackdropColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalBackdropCustomColor',
      title: 'Custom Modal Backdrop Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalBackdropColorType !== 'custom',
    },

    // Modal Content Colors
    {
      name: 'modalClientNameColorType',
      title: 'Client Name Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'modalClientNameColorShade',
      title: 'Client Name Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.modalClientNameColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalClientNameCustomColor',
      title: 'Custom Client Name Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalClientNameColorType !== 'custom',
    },
    {
      name: 'modalDateColorType',
      title: 'Date Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'modalDateColorShade',
      title: 'Date Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.modalDateColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalDateCustomColor',
      title: 'Custom Date Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalDateColorType !== 'custom',
    },
    {
      name: 'modalDividerColorType',
      title: 'Divider Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      description: 'Color of the line between description and contributions',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'secondary',
    },
    {
      name: 'modalDividerColorShade',
      title: 'Divider Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 80,
      hidden: ({ parent }) => parent?.modalDividerColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalDividerCustomColor',
      title: 'Custom Divider Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalDividerColorType !== 'custom',
    },
    {
      name: 'modalDescriptionColor',
      title: 'Description Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'base',
    },
    {
      name: 'modalContributionsTitleColorType',
      title: 'Contributions Title Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
    },
    {
      name: 'modalContributionsTitleColorShade',
      title: 'Contributions Title Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 0,
      hidden: ({ parent }) =>
        parent?.modalContributionsTitleColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalContributionsTitleCustomColor',
      title: 'Custom Contributions Title Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) =>
        parent?.modalContributionsTitleColorType !== 'custom',
    },
    {
      name: 'modalContributionsTextColor',
      title: 'Contributions Text Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Base', value: 'base' },
          { title: 'Muted', value: 'muted' },
          { title: 'Contrast', value: 'contrast' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'base',
    },
    {
      name: 'modalBulletColorType',
      title: 'Bullet Color',
      type: 'string',
      group: 'modalStyling',
      fieldset: 'modalFields',
      options: {
        list: [
          { title: 'Primary', value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Accent', value: 'accent' },
          { title: 'Custom', value: 'custom' },
        ],
      },
      initialValue: 'accent',
    },
    {
      name: 'modalBulletColorShade',
      title: 'Bullet Shade',
      type: 'number',
      group: 'modalStyling',
      fieldset: 'modalFields',
      initialValue: 0,
      hidden: ({ parent }) => parent?.modalBulletColorType === 'custom',
      components: { input: BackgroundShadeInput },
    },
    {
      name: 'modalBulletCustomColor',
      title: 'Custom Bullet Color',
      type: 'simplerColor',
      group: 'modalStyling',
      fieldset: 'modalFields',
      hidden: ({ parent }) => parent?.modalBulletColorType !== 'custom',
    },

    // Case Studies
    {
      name: 'caseStudies',
      title: 'Case Studies',
      type: 'array',
      group: 'caseStudies',
      fieldset: 'caseStudiesFields',
      of: [
        {
          type: 'reference',
          to: [{ type: 'caseStudy' }],
        },
      ],
      description:
        'Select and arrange the case studies to display on this page. Case studies are managed in the Case Studies collection.',
    },
  ],
  preview: {
    select: {
      title: 'title',
    },
    prepare({ title }) {
      return {
        title: title || 'Case Studies Page',
      };
    },
  },
});
